### ISSUE TITLE
TaskScheduler.UnobservedTaskException

### ISSUE THREAD

**Issue by nberardi** [Fody/AsyncErrorHandler#14]
How does this differ from?
`TaskScheduler.UnobservedTaskException += HandleException;`

**Comment by SimonCropp** [comment]
not sure. TBH never used it. have you done some testing?

**Comment by nberardi** [comment]
It is one of the global handler that I hook up in my apps to catch exceptions. Here is a good explanation. It handles some edge cases that this Fody misses with abandoned Tasks that are no longer observed. 

http://tpodolak.com/blog/2015/08/10/tpl-exception-handling-and-unobservedtaskexception-issue/

Basically anything running in a task that lets an exception bubble up will be caught here. However that leaves the async/await processes which throw exceptions "normally" but they can be caught with 'AppDomain.UnhandledException'

https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx

**Comment by icnocop** [comment]
Hooking up to the `TaskScheduler.UnobservedTaskException` event isn't supported in partial-trust applications.

[MSDN: TaskScheduler.UnobservedTaskException Event](https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler.unobservedtaskexception(v=vs.95).aspx)

Otherwise, the following exception occurs:

> Attempt by security transparent method 'MyApp.Main.ctor()' to access security critical method 'System.Threading.Tasks.TaskScheduler.add_UnobservedTaskException(System.EventHandler`1<System.Threading.Tasks.UnobservedTaskExceptionEventArgs>)' failed.
